import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'
import Typography from '@mui/material/Typography'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Pagination, FreeMode, Navigation, Thumbs } from 'swiper'
import 'swiper/css'
import 'swiper/css/free-mode'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/thumbs'
import Box from '@mui/material/Box'

const imgs = [
  {
    id: 1,
    name: 1,
    url: 'https://cdn.pixabay.com/photo/2022/06/25/23/41/ladybug-7284337_1280.jpg'
  },
  {
    id: 2,
    name: 1,
    url: 'https://cdn.pixabay.com/photo/2013/08/20/15/47/poppies-174276_1280.jpg'
  },
  {
    id: 3,
    name: 3,
    url: 'https://cdn.pixabay.com/photo/2013/07/18/20/26/sea-164989_1280.jpg'
  },
  {
    id: 4,
    name: 5,
    url: 'https://cdn.pixabay.com/photo/2022/07/12/17/12/dog-7317820_1280.jpg'
  }
]

export default function SwiperDemo() {
  const [thumbsSwiper, setThumbsSwiper] = useState(null)
  const pagination = {
    clickable: true,
    dynamicBullets: true,
    renderBullet: function (index, className) {
      return '<span class="' + className + '">' + (index + 1) + '</span>'
    }
  }
  const navigation = {
    prevEl: React.createElement('span')
    // nextEl: <span>nextEl </span>
  }

  return (
    <>
      <Head>
        <title>swiper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="w-[100%]">
        <Swiper
          className="mySwiper"
          modules={[Navigation, Pagination]}
          autoHeight={true}
          navigation={true}
          pagination={pagination}
          centeredSlides={true}
          // scrollbar={{ draggable: true }}
          // onSwiper={(swiper) => console.log(swiper)}
          // onSlideChange={() => console.log('slide change')}
        >
          {imgs.map(({ id, name, url }) => (
            <SwiperSlide key={id}>
              <Box className="mb-[50px] px-[50px]">
                <img src={url} alt={name}></img>
              </Box>
            </SwiperSlide>
          ))}
          {/* <span slot="container-start">Container Start</span> */}
          {/* <span slot="container-end">Container End</span>
          <span slot="wrapper-start">Wrapper Start</span>
          <span slot="wrapper-end">Wrapper End</span> */}
        </Swiper>
      </Box>

      <Box className="mt-10 p-20">
        <Swiper
          className="mySwiper"
          spaceBetween={10}
          navigation={true}
          thumbs={{
            swiper:
              thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null
          }}
          modules={[FreeMode, Navigation, Thumbs]}
        >
          {imgs.map(({ id, name, url }) => (
            <SwiperSlide key={id}>
              <img src={url} alt={name}></img>
            </SwiperSlide>
          ))}
        </Swiper>
        <Swiper
          className="mySwiper2"
          onSwiper={setThumbsSwiper}
          spaceBetween={10}
          slidesPerView={4}
          freeMode={true}
          watchSlidesProgress={true}
          modules={[FreeMode, Navigation, Thumbs]}
        >
          {imgs.map(({ id, name, url }) => (
            <SwiperSlide key={id}>
              <img src={url} alt={name}></img>
            </SwiperSlide>
          ))}
          {/* <span slot="container-start">Container Start</span>
          <span slot="container-end" className="block w-[100px] h-[100px]">
            Container End
          </span>
          <span slot="wrapper-start">Wrapper Start</span>
          <span slot="wrapper-end" className="block w-[100px] h-[100px]">
            Wrapper End
          </span> */}
        </Swiper>
      </Box>
    </>
  )
}
