import Head from 'next/head'
import Image from 'next/image'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'
import Typography from '@mui/material/Typography'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/scrollbar'
import Box from '@mui/material/Box'
import React, { useState } from 'react'
import Dialog from '@mui/material/Dialog'
import DialogActions from '@mui/material/DialogActions'
import DialogContent from '@mui/material/DialogContent'
import DialogContentText from '@mui/material/DialogContentText'
import DialogTitle from '@mui/material/DialogTitle'

const imgs = [
  {
    id: 1,
    name: 1,
    url: 'https://cdn.pixabay.com/photo/2022/06/25/23/41/ladybug-7284337_1280.jpg'
  },
  {
    id: 2,
    name: 1,
    url: 'https://cdn.pixabay.com/photo/2013/08/20/15/47/poppies-174276_1280.jpg'
  },
  {
    id: 3,
    name: 3,
    url: 'https://cdn.pixabay.com/photo/2013/07/18/20/26/sea-164989_1280.jpg'
  },
  {
    id: 4,
    name: 5,
    url: 'https://cdn.pixabay.com/photo/2022/07/12/17/12/dog-7317820_1280.jpg'
  }
]

export default function ModelDemo() {
  const [open, setOpen] = useState(false)
  const [scroll, setScroll] = useState('paper')
  const handleClickOpen = () => {
    setOpen(true)
    // setScroll(scrollType)
  }

  const handleClose = () => {
    setOpen(false)
  }

  return (
    <>
      <Head>
        <title>model</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="w-[100%] h-[500px]">
        <Button
          className="text-red font-[20px] bg-gray"
          onClick={handleClickOpen}
        >
          click
        </Button>
      </Box>
      <Dialog
        fullWidth={true}
        maxWidth="md"
        open={open}
        onClose={handleClose}
        scroll={scroll}
        aria-labelledby="scroll-dialog-title"
        aria-describedby="scroll-dialog-description"
      >
        <DialogTitle>{"Use Google's location service?"}</DialogTitle>
        <DialogContent>
          <DialogContentText id="scroll-dialog-description" tabIndex={-1}>
            {[...new Array(50)]
              .map(
                () => `Cras mattis consectetur purus sit amet fermentum.
Cras justo odio, dapibus ac facilisis in, egestas eget quam.
Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
Praesent commodo cursus magna, vel scelerisque nisl consectetur et.`
              )
              .join('\n')}
          </DialogContentText>
          <Swiper
            className="mySwiper"
            modules={[Navigation, Pagination]}
            autoHeight={true}
            navigation={true}
            pagination={true}
          >
            {imgs.map(({ id, name, url }) => (
              <SwiperSlide key={id}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={url} alt={name}></img>
              </SwiperSlide>
            ))}
            <span slot="container-start">Container Start</span>
            {/* <span slot="container-end">Container End</span>
          <span slot="wrapper-start">Wrapper Start</span>
          <span slot="wrapper-end">Wrapper End</span> */}
          </Swiper>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose}>Disagree</Button>
          <Button onClick={handleClose}>Agree</Button>
        </DialogActions>
      </Dialog>
    </>
  )
}
